### PR TITLE
add apple touch icon to prevent 500 errors

### PR DESCRIPTION
**Pull request by Rabid-Dan**
Raygun is showing HTTP 500 error messages due to the lack of an apple-touch-icon file https://app.raygun.com/crashreporting/w693o4/errors/2065476480 

This branch adds a square nzsl logo image file so that the erroring path resolves and raygun stops sending messages.

### CODE REVIEW

**Comment by joshmcarthur** [comment]
@Rabid-Dan it's probably a good idea to place this file in `app/assets/images`, so that we get all the benefits of the asset pipeline. You'll need to investigate what part of the layout file is loading this icon - it will be something in the document `head`

**Comment by Rabid-Dan** [comment]
@joshmcarthur yeah theres a link tag in the head that references it. I tried originally to add it to the path you mentioned but it didnt like it being there. I suspect it has something to do with the link tag referencing favicons and the favicon being stored in the public folder but ill take another look and see if I can get it to work properly so it can be stored there.

**Comment by Rabid-Dan** [comment]
So it turns out the routing actually tries to route urls that look like that to the PagesController#show action. The reason that the original solution worked was because it was able to find the icon to show through the public folder, but moving it to the assets/images folder borked things. I've added a copy there and changed the relative path for the apple touch icon link tag, but it feels like its probably a good idea to leave the copy in the public folder too (unless you've got suggestions?)

**Comment by ben-rabid** [comment]
Can we keep this moving please? It's eating into our raygun monthly limits.

**Comment by Rabid-Dan** [comment]
Yep sure thing, I'm going to close this request and open a new one into the nzsl branch because thats apparently the proper process now

**Pull request closed without merging**
